# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: en
title: Decentralized Web Histories
email: infominer@protonmail.com
description: An exploration of P2P and decentralized tech throughout the years.
# Webmentions - leave blank (remove "yes") if you would not like to receive & display webmentions from other sites
webmentions:

github                   : [metadata]
repository               : "sourcecrypto/decentralized-web"


baseurl: "/decentralized-web" # the subpath of your site, e.g. /blog
url: "https://sourcecrypto.pub" # the base hostname & protocol for your site
twitter_username: infominer33
github_username:  infominer33


# Can be over ridden with author: in Front Matter
author: Infominer
bio: "Full-Time Web-worker: Crypto-Curation and Histories ⧉ Bitcoin, Blockchain, DecentralizedID ⧉ Research, Publishing, Indieweb ⧉ her/him"

# Expecting a full url, not relative to site.url
author_img: https://infominer.id/assets/img/infolit.png

# Build settings
markdown: kramdown

twitter:
  username: sourcecrypto

og_image: https://sourcecrypto.pub/decentralized-web/assets/images/Decentralized-Web-Histories.png


plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
