# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: en
title: Decentralized Web Histories
email: infominer@protonmail.com
description: A Jekyll quick start to getting up and going with the indieweb.
# Webmentions - leave blank (remove "yes") if you would not like to receive & display webmentions from other sites
webmentions:

github                   : [metadata]
repository               : "sourcecrypto/decentralized-web"


baseurl: "/decentralized-web" # the subpath of your site, e.g. /blog
url: "http://sourcecrypto.pub/" # the base hostname & protocol for your site
twitter_username: infominer33
github_username:  infominer33


# Can be over ridden with author: in Front Matter
author: Infominer
bio: "Full-Time Web-worker: Crypto-Curation and Histories ⧉ Bitcoin, Blockchain, DecentralizedID ⧉ Research, Publishing, Indieweb ⧉ her/him"

# Expecting a full url, not relative to site.url
author_img: https://infominer.id/assets/img/infolit.png

# Build settings
markdown: kramdown

twitter:
  username: infominer33
  card: summary_large_image
  image: 

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  
paginate: 5
